<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Role;

class RoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Role::create([
            'role_name' => 'ALL',
            'is_kintai_mgt_func_available' => 1,
            'is_base_check_available' => 1,
            'is_kintai_operation_available' => 1,
            'is_employee_mgt_func_available' => 1,
            'is_employee_operation_available' => 1,
            'is_base_mgt_func_available' => 1,
            'is_manual_punch_available' => 1,
            'is_customer_mgt_func_available' => 1,
            'is_kintai_close_available' => 1,
            'is_download_func_available' => 1,
            'is_kintai_report_download_available' => 1,
            'is_data_download_available' => 1,
            'is_other_func_available' => 1,
            'is_accounting_mgt_func_available' => 1,
            'is_system_mgt_func_available' => 1,
            'is_user_mgt_available' => 1,
            'is_role_mgt_available' => 1,
            'is_holiday_mgt_available' => 1,
            'is_access_mgt_available' => 1,
            'is_base_mgt_available' => 1,
            'is_lock_kintai_operation_available' => 1,
            'is_all_kintai_operation_available' => 1,
            'is_short_time_info_available' => 1,
            'is_all_base_operation_available' => 1,
        ]);
        Role::create([
            'role_name' => '経理',
            'is_kintai_mgt_func_available' => 1,
            'is_base_check_available' => 1,
            'is_kintai_operation_available' => 1,
            'is_employee_mgt_func_available' => 1,
            'is_employee_operation_available' => 1,
            'is_base_mgt_func_available' => 1,
            'is_manual_punch_available' => 1,
            'is_customer_mgt_func_available' => 1,
            'is_kintai_close_available' => 1,
            'is_download_func_available' => 1,
            'is_kintai_report_download_available' => 1,
            'is_data_download_available' => 1,
            'is_other_func_available' => 1,
            'is_accounting_mgt_func_available' => 1,
            'is_system_mgt_func_available' => 0,
            'is_user_mgt_available' => 0,
            'is_role_mgt_available' => 0,
            'is_holiday_mgt_available' => 0,
            'is_access_mgt_available' => 0,
            'is_base_mgt_available' => 0,
            'is_lock_kintai_operation_available' => 1,
            'is_all_kintai_operation_available' => 1,
            'is_short_time_info_available' => 1,
            'is_all_base_operation_available' => 1,
        ]);
        Role::create([
            'role_name' => '本社',
            'is_kintai_mgt_func_available' => 1,
            'is_base_check_available' => 1,
            'is_kintai_operation_available' => 1,
            'is_employee_mgt_func_available' => 1,
            'is_employee_operation_available' => 0,
            'is_base_mgt_func_available' => 1,
            'is_manual_punch_available' => 1,
            'is_customer_mgt_func_available' => 1,
            'is_kintai_close_available' => 0,
            'is_download_func_available' => 1,
            'is_kintai_report_download_available' => 1,
            'is_data_download_available' => 1,
            'is_other_func_available' => 1,
            'is_accounting_mgt_func_available' => 0,
            'is_system_mgt_func_available' => 0,
            'is_user_mgt_available' => 0,
            'is_role_mgt_available' => 0,
            'is_holiday_mgt_available' => 0,
            'is_access_mgt_available' => 0,
            'is_base_mgt_available' => 0,
            'is_lock_kintai_operation_available' => 0,
            'is_all_kintai_operation_available' => 0,
            'is_short_time_info_available' => 1,
        ]);
        Role::create([
            'role_name' => '所長',
            'is_kintai_mgt_func_available' => 1,
            'is_base_check_available' => 1,
            'is_kintai_operation_available' => 1,
            'is_employee_mgt_func_available' => 1,
            'is_employee_operation_available' => 1,
            'is_base_mgt_func_available' => 1,
            'is_manual_punch_available' => 1,
            'is_customer_mgt_func_available' => 1,
            'is_kintai_close_available' => 1,
            'is_download_func_available' => 1,
            'is_kintai_report_download_available' => 0,
            'is_data_download_available' => 1,
            'is_other_func_available' => 1,
            'is_accounting_mgt_func_available' => 0,
            'is_system_mgt_func_available' => 0,
            'is_user_mgt_available' => 0,
            'is_role_mgt_available' => 0,
            'is_holiday_mgt_available' => 0,
            'is_access_mgt_available' => 0,
            'is_base_mgt_available' => 0,
            'is_lock_kintai_operation_available' => 0,
            'is_all_kintai_operation_available' => 0,
            'is_short_time_info_available' => 0,
        ]);
        Role::create([
            'role_name' => '社員',
            'is_kintai_mgt_func_available' => 1,
            'is_base_check_available' => 1,
            'is_kintai_operation_available' => 0,
            'is_employee_mgt_func_available' => 0,
            'is_employee_operation_available' => 0,
            'is_base_mgt_func_available' => 0,
            'is_manual_punch_available' => 0,
            'is_customer_mgt_func_available' => 0,
            'is_kintai_close_available' => 0,
            'is_download_func_available' => 0,
            'is_kintai_report_download_available' => 0,
            'is_data_download_available' => 0,
            'is_other_func_available' => 0,
            'is_accounting_mgt_func_available' => 0,
            'is_system_mgt_func_available' => 0,
            'is_user_mgt_available' => 0,
            'is_role_mgt_available' => 0,
            'is_holiday_mgt_available' => 0,
            'is_access_mgt_available' => 0,
            'is_base_mgt_available' => 0,
            'is_lock_kintai_operation_available' => 0,
            'is_all_kintai_operation_available' => 0,
            'is_short_time_info_available' => 0,
        ]);
        Role::create([
            'role_name' => '打刻',
        ]);
    }
}
